source 'https://rubygems.org'

ruby '2.2.1'

gem 'rails', '4.2.1'
gem 'mysql2'
gem 'bootstrap-sass'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'turbolinks'
gem 'geocoder'
gem 'geocomplete_rails'
gem 'mapbox-rails'
gem 'devise'
gem 'autoprefixer-rails'
gem 'responders'
gem 'font-awesome-sass'
gem 'jquery-turbolinks'
gem 'gmaps4rails'
gem 'execjs'
gem 'therubyracer'
gem 'bootstrap-datepicker-rails'
gem 'progress_bar'
gem 'protected_attributes'
gem 'cancan'
gem 'leaflet-rails'
gem 'ransack', github: 'activerecord-hackery/ransack'
gem 'will_paginate', github: 'jonatack/will_paginate'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'haml-rails'
gem 'rails_12factor', group: :production

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'better_errors'
  gem 'binding_of_caller'
end
