source 'https://rubygems.org'

ruby '2.2.1'

gem 'rails', '4.2.1'
gem 'mysql2', '~> 0.3.18'
gem 'bootstrap-sass'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'carrierwave-crop'
gem 'turbolinks'
gem "iconv", "~> 1.0.3"
gem 'geocoder'
gem 'react-rails', '~> 1.6.0'
gem 'devise_invitable', '~> 1.5.2'
gem 'geocomplete_rails'
gem 'mapbox-rails'
gem 'cancancan'
gem "js-routes"
gem 'faker'
gem 'figaro'
gem 'rolify'
gem 'rmagick'
gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'
gem 'devise'
gem 'socialization'
gem 'mailboxer', git: 'git://github.com/ging/mailboxer.git'
gem 'public_activity'
gem 'autoprefixer-rails'
gem 'responders'
gem 'font-awesome-sass'
gem 'jquery-turbolinks'
gem 'roo'
gem 'gmaps4rails'
gem 'devise_token_auth'
gem 'omniauth-github', :github => 'intridea/omniauth-github'
gem 'omniauth-openid', :github => 'intridea/omniauth-openid'
gem 'execjs'
gem 'mechanize'
gem 'nokogiri'
gem 'therubyracer'
gem 'bootstrap-datepicker-rails'
gem 'progress_bar'
gem 'protected_attributes'
gem 'cancan'
gem 'erb2haml'
gem 'leaflet-rails'
gem 'ransack', github: 'activerecord-hackery/ransack'
gem 'will_paginate', github: 'jonatack/will_paginate'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'haml-rails'
gem 'rails_12factor', group: :production

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'better_errors'
  gem 'binding_of_caller'
end
