class Person < ActiveRecord::Base
  # These attributes are what will accessible throughout the website. If the attribute is not listed here, it cannot work with the website.
  attr_accessible :Name,
                  :Location,
                  :latitude,
                  :longitude,
                  :bio,
                  :title,
                  :donor,
                  :dateStart,
                  :dateEnd,
                  :keyword,
                  :id,
                  :activeDateStart,
                  :activeDateEnd,
                  :active
  # Geocoder gem that takes in location and turns it into lat and long.
  geocoded_by :Location
  after_validation :geocode, :if => :Location_changed?

  COUNTRIES = {
    "Aruba" => "ABW",
    "Afghanistan" => "AFG",
    "Angola" => "AGO",
    "Anguilla" => "AIA",
    "Åland Islands" => "ALA",
    "Albania" => "ALB",
    "Andorra" => "AND",
    "United Arab Emirates" => "ARE",
    "Argentina" => "ARG",
    "Armenia" => "ARM",
    "American Samoa" => "ASM",
    "Antarctica"	=>	"ATA",
    "French Southern Territories"	=>	"ATF",
    "Antigua and Barbuda	"	=>	"ATG",
    "Australia"	=>	"AUS",
    "Austria"	=>	"AUT",
    "Azerbaijan"	=>	"AZE",
    "Burundi"	=>	"BDI",
    "Belgium"	=>	"BEL",
    "Benin"	=>	"BEN",
    "Bonaire, Sint Eustatius and Saba"	=>	"BES",
    "Burkina Faso"	=>	"BFA",
    "Bangladesh"	=>	"BGD",
    "Bulgaria"	=>	"BGR",
    "Bahrain"	=>	"BHR",
    "Bahamas"	=>	"BHS",
    "Bosnia and Herzegovina"	=>	"BIH",
    "Saint Barthélemy"	=>	"BLM",
    "Belarus"	=>	"BLR",
    "Belize"	=>	"BLZ",
    "Bermuda"	=>	"BMU",
    "Bolivia, Plurinational State of"	=>	"BOL",
    "Brazil"	=>	"BRA",
    "Barbados"	=>	"BRB",
    "Brunei Darussalam"	=>	"BRN",
    "Bhutan"	=>	"BTN",
    "Bouvet Island"	=>	"BVT",
    "Botswana"	=>	"BWA",
    "Central African Republic"	=>	"CAF",
    "Canada"	=>	"CAN",
    "Cocos (Keeling) Islands"	=>	"CCK",
    "Switzerland"	=>	"CHE",
    "Chile"	=>	"CHL",
    "China"	=>	"CHN",
    "Côte d'Ivoire"	=>	"CIV",
    "Cameroon"	=>	"CMR",
    "Congo, the Democratic Republic of the"	=>	"COD",
    "Congo"	=>	"COG",
    "Cook Islands"	=>	"COK",
    "Colombia"	=>	"COL",
    "Comoros"	=>	"COM",
    "Cabo Verde"	=>	"CPV",
    "Costa Rica"	=>	"CRI",
    "Cuba"	=> "CUB",
    "Curaçao"	=>	"CUW",
    "Christmas Island"	=>	"CXR",
    "Cayman Islands"	=>	"CYM",
    "Cyprus"	=>	"CYP",
    "Czech Republic"	=>	"CZE",
    "Germany"	=>	"DEU",
    "Djibouti"	=>	"DJI",
    "Dominica"	=>	"DMA",
    "Denmark"	=>	"DNK",
    "Dominican Republic"	=>	"DOM",
    "Algeria"	=>	"DZA",
    "Ecuador"	=>	"ECU",
    "Egypt"	=>	"EGY",
    "Eritrea"	=>	"ERI",
    "Western Sahara"	=>	"ESH",
    "Spain"	=>	"ESP",
    "Estonia"	=>	"EST",
    "Ethiopia"	=>	"ETH",
    "Finland"	=>	"FIN",
    "Fiji"	=>	"FJI",
    "Falkland Islands (Malvinas)"	=>	"FLK",
    "France"	=>	"FRA",
    "Faroe Islands"	=>	"FRO",
    "Micronesia, Federated States of"	=>	"FSM",
    "Gabon"	=>	"GAB",
    "United Kingdom"	=>	"GBR",
    "Georgia"	=>	"GEO",
    "Guernsey"	=>	"GGY",
    "Ghana"	=>	"GHA",
    "Gibraltar"	=>	"GIB",
    "Guinea"	=>	"GIN",
    "Guadeloupe"	=>	"GLP",
    "Gambia"	=>	"GMB",
    "Guinea-Bissau"	=>	"GNB",
    "Equatorial Guinea"	=>	"GNQ",
    "Greece"	=>	"GRC",
    "Grenada"	=>	"GRD",
    "Greenland"	=>	"GRL",
    "Guatemala"	=>	"GTM",
    "French Guiana"	=>	"GUF",
    "Guam"	=>	"GUM",
    "Guyana"	=>	"GUY",
    "Hong Kong"	=>	"HKG",
    "Heard Island and McDonald Islands"	=>	"HMD",
    "Honduras"	=>	"HND",
    "Croatia"	=>	"HRV",
    "Haiti"	=>	"HTI",
    "Hungary"	=>	"HUN",
    "Indonesia"	=>	"IDN",
    "Isle of Man"	=>	"IMN",
    "India"	=>	"IND",
    "British Indian Ocean Territory"	=>	"IOT",
    "Ireland"	=>	"IRL",
    "Iran, Islamic Republic of"	=>	"IRN",
    "Iraq"	=>	"IRQ",
    "Iceland"	=>	"ISL",
    "Israel"	=>	"ISR",
    "Italy"	=>	"ITA",
    "Jamaica"	=>	"JAM",
    "Jersey"	=>	"JEY",
    "Jordan"	=>	"JOR",
    "Japan"	=>	"JPN",
    "Kazakhstan"	=>	"KAZ",
    "Kenya"	=>	"KEN",
    "Kyrgyzstan"	=>	"KGZ",
    "Cambodia"	=>	"KHM",
    "Kiribati"	=>	"KIR",
    "Saint Kitts and Nevis"	=>	"KNA",
    "Korea, Republic of"	=>	"KOR",
    "Kuwait"	=>	"KWT",
    "Lao People's Democratic Republic"	=>	"LAO",
    "Lebanon"	=>	"LBN",
    "Liberia"	=>	"LBR",
    "Libya"	=>	"LBY",
    "Saint Lucia"	=>	"LCA",
    "Liechtenstein"	=>	"LIE",
    "Sri Lanka"	=>	"LKA",
    "Lesotho"	=>	"LSO",
    "Lithuania"	=>	"LTU",
    "Luxembourg"	=>	"LUX",
    "Latvia"	=>	"LVA",
    "Macao"	=>	"MAC",
    "Saint Martin (French part)"	=>	"MAF",
    "Morocco"	=>	"MAR",
    "Monaco"	=>	"MCO",
    "Moldova, Republic of"	=>	"MDA",
    "Madagascar"	=>	"MDG",
    "Maldives"	=>	"MDV",
    "Mexico"	=>	"MEX",
    "Marshall Islands"	=>	"MHL",
    "Macedonia, the former Yugoslav Republic of"	=>	"MKD",
    "Mali"	=>	"MLI",
    "Malta"	=>	"MLT",
    "Myanmar"	=>	"MMR",
    "Montenegro"	=>	"MNE",
    "Mongolia"	=>	"MNG",
    "Northern Mariana Islands"	=>	"MNP",
    "Mozambique"	=>	"MOZ",
    "Mauritania"	=>	"MRT",
    "Montserrat"	=>	"MSR",
    "Martinique"	=>	"MTQ",
    "Mauritius"	=>	"MUS",
    "Malawi"	=>	"MWI",
    "Malaysia"	=>	"MYS",
    "Mayotte"	=>	"MYT",
    "Namibia"	=>	"NAM",
    "New Caledonia"	=>	"NCL",
    "Niger"	=>	"NER",
    "Norfolk Island"	=>	"NFK",
    "Nigeria"	=>	"NGA",
    "Nicaragua"	=>	"NIC",
    "Niue"	=>	"NIU",
    "Netherlands"	=>	"NLD",
    "Norway"	=>	"NOR",
    "Nepal"	=>	"NPL",
    "Nauru"	=>	"NRU",
    "New Zealand"	=>	"NZL",
    "Oman"	=>	"OMN",
    "Pakistan"	=>	"PAK",
    "Panama"	=>	"PAN",
    "Pitcairn"	=>	"PCN",
    "Peru"	=>	"PER",
    "Philippines"	=>	"PHL",
    "Palau"	=>	"PLW",
    "Papua New Guinea"	=>	"PNG",
    "Poland"	=>	"POL",
    "Puerto Rico"	=>	"PRI",
    "Korea, Democratic People's Republic of"	=>	"PRK",
    "Portugal"	=>	"PRT",
    "Paraguay"	=>	"PRY",
    "Palestine, State of"	=>	"PSE",
    "French Polynesia"	=>	"PYF",
    "Qatar"	=>	"QAT",
    "Réunion"	=>	"REU",
    "Romania"	=>	"ROU",
    "Russian Federation"	=>	"RUS",
    "Rwanda"	=>	"RWA",
    "Saudi Arabia"	=>	"SAU",
    "Sudan"	=>	"SDN",
    "Senegal"	=>	"SEN",
    "Singapore"	=>	"SGP",
    "South Georgia and the South Sandwich Islands"	=>	"SGS",
    "Saint Helena, Ascension and Tristan da Cunha"	=>	"SHN",
    "Svalbard and Jan Mayen"	=>	"SJM",
    "Solomon Islands"	=>	"SLB",
    "Sierra Leone"	=>	"SLE",
    "El Salvador"	=>	"SLV",
    "San Marino"	=>	"SMR",
    "Somalia"	=>	"SOM",
    "Saint Pierre and Miquelon"	=>	"SPM",
    "Serbia"	=>	"SRB",
    "South Sudan"	=>	"SSD",
    "Sao Tome and Principe"	=>	"STP",
    "Suriname"	=>	"SUR",
    "Slovakia"	=>	"SVK",
    "Slovenia"	=>	"SVN",
    "Sweden"	=>	"SWE",
    "Swaziland"	=>	"SWZ",
    "Sint Maarten (Dutch part)"	=>	"SXM",
    "Seychelles"	=>	"SYC",
    "Syrian Arab Republic"	=>	"SYR",
    "Turks and Caicos Islands"	=>	"TCA",
    "Chad"	=>	"TCD",
    "Togo"	=>	"TGO",
    "Thailand"	=>	"THA",
    "Tajikistan"	=>	"TJK",
    "Tokelau"	=>	"TKL",
    "Turkmenistan"	=>	"TKM",
    "Timor-Leste"	=>	"TLS",
    "Tonga"	=>	"TON",
    "Trinidad and Tobago"	=>	"TTO",
    "Tunisia"	=>	"TUN",
    "Turkey"	=>	"TUR",
    "Tuvalu"	=>	"TUV",
    "Taiwan, Province of China"	=>	"TWN",
    "Tanzania, United Republic of"	=>	"TZA",
    "Uganda"	=>	"UGA",
    "Ukraine"	=>	"UKR",
    "United States Minor Outlying Islands"	=>	"UMI",
    "Uruguay"	=>	"URY",
    "United States"	=>	"USA",
    "Uzbekistan"	=>	"UZB",
    "Holy See (Vatican City State)"	=>	"VAT",
    "Saint Vincent and the Grenadines"	=>	"VCT",
    "Venezuela, Bolivarian Republic of"	=>	"VEN",
    "Venezuela"	=>	"VEN",
    "Virgin Islands, British"	=>	"VGB",
    "Virgin Islands, U.S."	=>	"VIR",
    "Viet Nam"	=>	"VNM",
    "Vanuatu"	=>	"VUT",
    "Wallis and Futuna"	=>	"WLF",
    "Samoa"	=>	"WSM",
    "Yemen"	=>	"YEM",
    "South Africa"	=>	"ZAF",
    "Zambia"	=>	"ZMB",
    "Zimbabwe"	=>	"ZWE"
  }

  STATES = {
  "AL" => "Alabama",
  "AK" => "Alaska",
  "AZ" => "Arizona",
  "AR" => "Arkansas",
  "CA" => "California",
  "CO" => "Colorado",
  "CT" => "Connecticut",
  "DE" => "Delaware",
  "FL" => "Florida",
  "GA" => "Georgia",
  "HI" => "Hawaii",
  "ID" => "Idaho",
  "IL" => "Illinois",
  "IN" => "Indiana",
  "IA" => "Iowa",
  "KS" => "Kansas",
  "KY" => "Kentucky",
  "LA" => "Louisiana",
  "ME" => "Maine",
  "MD" => "Maryland",
  "MA" => "Massachusetts",
  "MI" => "Michigan",
  "MN" => "Minnesota",
  "MS" => "Mississippi",
  "MO" => "Missouri",
  "MT" => "Montana",
  "NE" => "Nebraska",
  "NV" => "Nevada",
  "NH" => "New Hampshire",
  "NJ" => "New Jersey",
  "NM" => "New Mexico",
  "NY" => "New York",
  "NC" => "North Carolina",
  "ND" => "North Dakota",
  "OH" => "Ohio",
  "OK" => "Oklahoma",
  "OR" => "Oregon",
  "PA" => "Pennsylvania",
  "RI" => "Rhode Island",
  "SC" => "South Carolina",
  "SD" => "South Dakota",
  "TN" => "Tennessee",
  "TX" => "Texas",
  "UT" => "Utah",
  "VT" => "Vermont",
  "VA" => "Virginia",
  "WA" => "Washington",
  "WV" => "West Virginia",
  "WI" => "Wisconsin",
  "WY" => "Wyoming"
}

  def active?
    self.activeDateEnd > Time.now.localtime
  end

  def inField?
    self.dateEnd > Time.now.localtime
  end

  def update_active_status
    if self.active?
      self.update_attribute(:active, true)
    else
      self.update_attribute(:active, false)
    end
  end

  def update_donor_status
    if self.inField?
      self.update_attribute(:donor, true)
    else
      self.update_attribute(:donor, false)
    end
  end

  def country
    location_tos = self.Location.to_s
    COUNTRIES.each do |key, value|
      if location_tos.include?(key)
        self.update_attribute(:abr_Country, COUNTRIES[key])
      end
    end
  end

  def findLocation
    bio_tos = self.bio.to_s
    COUNTRIES.each do |key, value|
      if bio_tos.include?(key)
        if self.Location?
          self.update_attribute(:Location, key)
          :geocode
        end
      end
    end
  end

  def state
    STATES.each do |key, value|
    location_tos = self.Location.to_s
    if location_tos.include?(key)
      self.update_attribute(:full_State, STATES[key])
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    super - ['id', 'created_at', 'longitude', 'latitude', 'updated_at', 'full_State']
  end
end
end
